### ISSUE TITLE
Wie zum Laufen bekommen?

### ISSUE THREAD

**Issue by D3rJust1n** [jzbor/lisho#3]
Maybe bin ich einfach nur dumm, aber wie krieg ich das zum Laufen?😅

**Comment by jzbor** [comment]
Hi, im Prinzip sinds drei Schritte:
1. Kompilieren/installieren (`cargo build` bzw. `cargo install`) oder zum testen geht auch `cargo run`
2. Eine Datei mit Weiterleitungen erstellen (wie in dem Beispiel im README)
3. Das Programm aus dem ersten Schritt ausführen, mit der Datei aus Schritt 2 als erstem Argument: `pfad/nach/lisho weiterleitungen.txt`. Alternativ kannst du zum testen auch `cargo run weiterleitungen.txt` verwenden.

Das ganze setzt vorraus, dass du auf einem Unixoiden Betriebssystem unterwegs bist und [Rust installiert hast](https://www.rust-lang.org/tools/install). Es kann sein, dass es auch unter Windows geht, aber ich habs nur mit Linux getestet.

Wenn du bei einem der Schritte Probleme hast musst dus vielleicht nochmal etwas genauer beschreiben.

**Comment by jzbor** [comment]
Closing, because no feedback or clear issue was provided. Feel free to reopen, if there is an actual issue.
